# name: transition-for-branch-create
# on:
#   create:
#   push:

# jobs:
#   push-event:
#     runs-on: ubuntu-latest
#     steps:
#       - name: details
#         run: echo '${{ toJSON(github) }}'

#       - name: Login
#         uses: atlassian/gajira-login@master
#         env:
#           JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
#           JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
#           JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

#       - name: Update status to in progress
#         shell: bash
#         run: |
#           Response=$(curl --location --request GET "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.jira-issue-push.outputs.issue }}?fields=status" \
#           --header 'Accept: application/json' \
#           --user '${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}' )
#            echo "##[set-output name=status;]$(echo $Response | jq '.fields.status.name')"
#            echo $Response | jq '.fields.status.name'
#            status=$(echo $Response | jq '.fields.status.name')

#           if [[ $status == "To Do" ]]; then
#             echo "Your issue on JIRA still not Active."
#             exit 1
#           fi
