name: transition-for-pull-request
on: [pull_request]
jobs:
  transition-for-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: timestamp of issue transition
        id: timestamp
        run: echo $(date)
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Find in commit messages
        id: jira-issue
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: ${{ github.event.ref }}
      - name: Transition issue
        id: transition
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.jira-issue.outputs.issue }}
          transition: 'In Review'
      - name: Comment on issue
        uses: atlassian/gajira-comment@master
        with:
          issue: ${{ steps.jira-issue.outputs.issue }}
          comment: '${{ github.event.pusher.name }} branch created to repository: ${{ steps.jira-issue.outputs.issue }} ${{ github.event.repository.full_name }} branch: ${{ github.event.repository.base }}'
