name: transition-for-branch-create
on:
  create:
  push:

jobs:
  push-event:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find jira-issue for push
        id: jira-issue-push
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: ${{ github.event.ref }}

      - name: Get Issue Status
        id: jira-issue-status
        shell: bash
        run: |
          Response=$(curl --location --request GET "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.jira-issue-push.outputs.issue }}?fields=status" \
          --header 'Accept: application/json' \
          --header "Authorization: ${{ inputs.jira-token }}" )
           echo "##[set-output name=status;]$(echo $Response | jq '.fields.status.name')"
           echo $Response | jq '.fields.status.name'

      - name: on-push-transition-to-in-progress
        if: ${{ steps.jira-issue-status.outputs.status }} == 'To Do'
        id: on-push-transition-to-in-progress
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.jira-issue-push.outputs.issue }}
          transition: 'In Progress'

      - name: Comment on issue
        uses: atlassian/gajira-comment@master
        with:
          issue: ${{ steps.jira-issue-push.outputs.issue }}
          comment: '${{ github.event.pusher.name }} branch created to repository: ${{steps.jira-issue-push.outputs.issue }} ${{ github.event.repository.full_name }} branch: ${{ github.event.repository.base }}'
