# name: transition-for-branch-create
# on:
#   # create:
#   push:
#   pull_request:
#     types: [opened, edited, reopened, synchronize]
#   pull_request_review:
#     types: [submitted]

# jobs:
#   push-event:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Login
#         uses: atlassian/gajira-login@master
#         env:
#           JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
#           JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
#           JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

#       - name: Find jira-issue for push
#         if: github.event_name == 'push'
#         id: jira-issue-push
#         uses: atlassian/gajira-find-issue-key@master
#         with:
#           string: ${{ github.event.ref }}

#       - name: on-push-transition-to-in-progress
#         if: github.event_name == 'push'
#         id: on-push-transition-to-in-progress
#         uses: atlassian/gajira-transition@master
#         with:
#           issue: ${{ steps.jira-issue-push.outputs.issue }}
#           transition: 'In Progress'

#       - name: Comment on issue
#         if: github.event_name == 'push'
#         uses: atlassian/gajira-comment@master
#         with:
#           issue: ${{ steps.jira-issue-push.outputs.issue }}
#           comment: '${{ github.event.pusher.name }} branch created to repository: ${{steps.jira-issue-push.outputs.issue }} ${{ github.event.repository.full_name }} branch: ${{ github.event.repository.base }}'

#   pull-request-event:
#     runs-on: ubuntu-latest
#     needs: [push-event]
#     steps:
#       - name: Login
#         uses: atlassian/gajira-login@master
#         env:
#           JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
#           JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
#           JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

#       - name: Find jira-issue for pull_request
#         if: github.event_name == 'pull_request'
#         id: jira-issue-pull-request
#         uses: atlassian/gajira-find-issue-key@master
#         with:
#           string: ${{ github.event.pull_request.title }}

#       - name: on-push-transition-to-in-review
#         if: github.event_name == 'pull_request'
#         id: on-pull-request-transition-to-in-review
#         uses: atlassian/gajira-transition@master
#         with:
#           issue: ${{ steps.jira-issue-pull-request.outputs.issue }}
#           transition: 'In Review'

#       - name: on-push-transition-to-in-review
#         if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
#         id: on-pull-request-synchronize-transition-to-in-review
#         uses: atlassian/gajira-transition@master
#         with:
#           issue: ${{ steps.jira-issue-pull-request.outputs.issue }}
#           transition: 'In Review'
