name: transition-for-branch-create
on:
  # create:
  push:
  pull_request:
    types: [opened, edited, reopened]
  pull_request_review:
    types: [submitted]

jobs:
  transition-for-branch-create:
    runs-on: ubuntu-latest
    steps:
      - name: timestamp of issue transition
        id: timestamp
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_ACTOR
          echo ${{ github.event.repo.name}}
          echo ${{ github.event}}

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find jira-issue for push
        if: $GITHUB_EVENT_NAME == "push"
        id: jira-issue-push
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: ${{ github.event.ref }}

      - name: Find jira-issue for pull_request
        if: $GITHUB_EVENT_NAME == "pull_request"
        id: jira-issue-pull-request
        uses: atlassian/gajira-find-issue-key@master
        with:
          from: commits

      - name: on-push-transition-to-in-progress
        if: $GITHUB_EVENT_NAME == "push"
        id: transition
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.jira-issue-push.outputs.issue }}
          transition: 'In Progress'

      - name: Comment on issue
        uses: atlassian/gajira-comment@master
        with:
          issue: ${{ steps.jira-issue.outputs.issue }}
          comment: '${{ github.event.pusher.name }} branch created to repository: ${{ steps.jira-issue.outputs.issue }} ${{ github.event.repository.full_name }} branch: ${{ github.event.repository.base }}'
