name: Jira issue transition
on: [push, pull_request, pull_request_review]
jobs:
  transition-jira-issue:
    runs-on: ubuntu-latest
    steps:
      - name: timestamp of issue transition
        id: timestamp
        run: echo $(date)
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Comment on issue
        uses: atlassian/gajira-comment@master
        with:
          issue: AUTO-1
          comment: '${{ github.event.pusher.name }} pushed to repository: ${{ steps.timestamp.outputs }} ${{ github.event.repository.full_name }} branch: ${{ github.event.repository.base }}'
      - name: Transition issue
        id: transition
        uses: atlassian/gajira-transition@master
        with:
          issue: AUTO-1
          transition: 'TO DO'
